# URI for database connection, leave empty if using address and credential settings directly
uri: ''
# List of MongoDB server addresses
address: [ localhost:27019 ]
# Name of the database
database: openim_v3
# Username for database authentication
username: malaka
# Password for database authentication
password: MalakaTT202406
# Maximum number of connections in the connection pool
maxPoolSize: 100
# Maximum number of retry attempts for a failed database connection
maxRetry: 10
